server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NFerrovia/final-github-ferrovia-nicolas
          searchPaths: config-microservices

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

